version: '3.8'

services:
  postgres1:
    image: postgres:13
    environment:
      POSTGRES_DB: db1
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres1-data:/var/lib/postgresql/data
    networks:
      - db-network

  postgres2:
    image: postgres:13
    environment:
      POSTGRES_DB: db2
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5467:5432"
    volumes:
      - postgres2-data:/var/lib/postgresql/data
    networks:
      - db-network

  postgres3:
    image: postgres:13
    environment:
      POSTGRES_DB: db3
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5478:5432"
    volumes:
      - postgres3-data:/var/lib/postgresql/data
    networks:
      - db-network

  app:
    build: .
    ports:
      - "50051:50051"
    depends_on:
      - postgres1
      - postgres2
      - postgres3
    networks:
      - db-network
    command: sh -c "sleep 10 && ./main"

volumes:
  postgres1-data:
  postgres2-data:
  postgres3-data:

networks:
  db-network:
    driver: bridge
